[package]
name = "athena"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.27", features = ["derive"] }
flate2 = "1.0.25"
futures = "0.3.25"
indicatif = "0.17.2"
relative-path = "1.7.2"
tar = "0.4.38"
tokio = { version = "1.22.0", features = ["full"] }
